export const COULD_NOT_CONNECT = 'COULD NOT CONNECT';

export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const USER_LOADING = 'USER_LOADING';
export const USER_GET = 'USER_GET';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_ERROR = 'USER_ERROR';

export const SCRAPING_LOADING = 'SCRAPING_LOADING';
export const SCRAPING_NEW = 'SCRAPING_NEW';
export const SCRAPING_GET = 'SCRAPING_GET';
export const SCRAPING_DELETE = 'SCRAPING_DELETE';
export const SCRAPING_TO_EXCEL = 'SCRAPING_TO_EXCEL';
export const SCRAPING_ERROR = 'SCRAPING_ERROR';

export const CAPTURE_LOADING = 'CAPTURE_LOADING';
export const CAPTURE_ERROR = 'CAPTURE_ERROR';
export const CAPTURE_START = 'CAPTURE_START';
export const CAPTURE_REMOVE = 'CAPTURE_REMOVE';
export const CAPTURE_APPEND = 'CAPTURE_APPEND';
export const CAPTURE_RESET = 'CAPTURE_RESET';

export const CAPTCHA_GET = 'CAPTCHA_GET';
export const CAPTCHA_ADD = 'CAPTCHA_ADD';
export const CAPTCHA_REMOVE = 'CAPTCHA_REMOVE';
export const CAPTCHA_EDIT = 'CAPTCHA_EDIT';

export const TARGET_GET = 'TARGET_GET';
export const TARGET_RESET = 'TARGET_RESET';

export const DETAILS_ADD = 'DETAILS_ADD';
export const DETAILS_REMOVE = 'DETAILS_REMOVE';
export const DETAILS_REMOVE_ALL = 'DETAILS_REMOVE_ALL';
export const DETAILS_ADD_FOLLOWLINKIDENTIFIER = 'DETAILS_ADD_FOLLOWLINKIDENTIFIER';
export const DETAILS_ADD_FOLLOWLINKS = 'DETAILS_ADD_FOLLOWLINKS';
export const DETAILS_ADD_MULTIPLE_SELECTOR = 'DETAILS_ADD_MULTIPLE_SELECTOR';
export const DETAILS_PUPPETEER_BROWSER_REFERENCE_SET = 'DETAILS_PUPPETEER_BROWSER_REFERENCE_SET';
export const DETAILS_PUPPETEER_MAIN_URL_SET = 'DETAILS_PUPPETEER_MAIN_URL_SET';
export const DETAILS_PUPPETEER_FOLLOWLINK_URL_SET = 'DETAILS_PUPPETEER_FOLLOWLINK_URL_SET';
export const DETAILS_SET_SEARCHURLS = 'DETAILS_SET_SEARCHURLS';
